#!/bin/sh

THRESHOLD=30
THRESHOLDJUMP=1
THRESHOLDMAX=200
EXTEND=false
CONFIDENCETHRESHOLD=0.01
CONFIDENCETHRESHOLDMAX=0.2
CONFIDENCETHRESHOLDJUMP=0.01
BLEACHING=0
BLEACHINGMAX=20
BLEACHINGJUMP=1
NUMBITSADDRS=2
NUMBITSADDRSJUMP=1
NUMBITSADDRSMAX=30

while [ $THRESHOLD -lt $THRESHOLDMAX ]
do
    while [ $(echo "$CONFIDENCETHRESHOLD < $CONFIDENCETHRESHOLDMAX" | bc -l) ]
    do
        while [ $BLEACHING -lt $BLEACHINGMAX ]
        do
            while [ $NUMBITSADDRS -lt $NUMBITSADDRSMAX ]
            do
                ./bin/mnistWisard.out 0 $NUMBITSADDRS $BLEACHING $CONFIDENCETHRESHOLD 0 0 $THRESHOLD > ./results/$NUMBITSADDRS-$BLEACHING-$CONFIDENCETHRESHOLD-$THRESHOLD-sequencial.txt
                ./bin/mnistWisard.out 1 $NUMBITSADDRS $BLEACHING $CONFIDENCETHRESHOLD 0 2 $THRESHOLD > ./results/$NUMBITSADDRS-$BLEACHING-$CONFIDENCETHRESHOLD-$THRESHOLD-threads2.txt
                ./bin/mnistWisard.out 1 $NUMBITSADDRS $BLEACHING $CONFIDENCETHRESHOLD 0 4 $THRESHOLD > ./results/$NUMBITSADDRS-$BLEACHING-$CONFIDENCETHRESHOLD-$THRESHOLD-threads4.txt
                echo "Done ./results/$NUMBITSADDRS-$BLEACHING-$CONFIDENCETHRESHOLD-$THRESHOLD-sequencial.txt"
                NUMBITSADDRS=`expr $NUMBITSADDRS+$NUMBITSADDRSJUMP`
            done
            BLEACHING=`expr $BLEACHING+$BLEACHINGJUMP`
        done
        CONFIDENCETHRESHOLD=`expr $CONFIDENCETHRESHOLD+$CONFIDENCETHRESHOLDJUMP`
    done
    THRESHOLD=`expr $THRESHOLD+$THRESHOLDJUMP`
done
